services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      #      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_DISABLE_POSTFIX: 'True'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
    profiles:
      - pgadmin

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-changeme}
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb:/data/db
      - mongoconfigdb:/data/configdb

  devapp:
    build: &build-dev
      context: https://github.com/johnniehay/oacapp.git#dev
#      context: ../../.
      dockerfile: docker/dev/Dockerfile
#      dockerfile: /home/johnnie/MEGA/code/oacapp/docker/dev/Dockerfile
      additional_contexts:
        local: ../../.
    env_file: &build-dev-env
      - ./.env.dev
    ports:
      - 146.64.84.46:3002:3000
    volumes:
      - devmedia:/app/public/media

  devapp-builder:
    build:
      <<: *build-dev
      target: builder
    env_file: *build-dev-env
    volumes:
      - devmedia:/app/public/media
      - ./datascripts:/app/datascripts


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongodb:
  mongoconfigdb:
  devmedia:
